TableCreation = '''
USE @@BD@@
GO

IF NOT EXISTS (SELECT SCHEMA_ID FROM sys.schemas WHERE [name] = '@@ESQUEMA@@')
BEGIN
	EXECUTE('CREATE SCHEMA @@ESQUEMA@@');
END;
GO

CREATE TABLE @@ESQUEMA@@.@@TABLA@@ (
  @@COLUMNAS@@
)
GO
'''

SQLServer_Schema = '''
SELECT
	TABLE_CATALOG
	,TABLE_NAME
	,TABLE_SCHEMA
	,CONCAT(COLUMN_NAME, ' ', UPPER(DATA_TYPE),
		CASE 
			WHEN DATA_TYPE LIKE '%int' THEN ''
			WHEN DATA_TYPE IN ('decimal', 'numeric') THEN CONCAT(' (', NUMERIC_PRECISION, ', ',  NUMERIC_SCALE, ')')
			WHEN DATA_TYPE LIKE '%char' THEN CONCAT(' (', CHARACTER_MAXIMUM_LENGTH, ')')
		END,
		IIF(IS_NULLABLE = 'YES', ' NULL', ' NOT NULL')
	) AS SYNTAXIS

FROM @@BD@@.INFORMATION_SCHEMA.COLUMNS

WHERE TABLE_SCHEMA = '@@ESQUEMA@@' AND TABLE_NAME = '@@TABLA@@'
'''