templates = {"sql_server": {
    "TableCreation" : '''
		USE @@DATABASE@@
		GO

		IF NOT EXISTS (SELECT SCHEMA_ID FROM sys.schemas WHERE [name] = '@@SCHEMA@@')
		BEGIN
			EXECUTE('CREATE SCHEMA @@SCHEMA@@');
		END;
		GO

		CREATE TABLE @@SCHEMA@@.@@TABLE@@ (
		@@COLUMNAS@@
		)
		GO
		''',
    "schema": '''
		SELECT
			ORDINAL_POSITION AS ORDEN
			,TABLE_CATALOG
			,TABLE_SCHEMA
			,TABLE_NAME 
			,COLUMN_NAME
			,IS_NULLABLE
			,DATA_TYPE
			,CHARACTER_MAXIMUM_LENGTH
			,NUMERIC_PRECISION
			,NUMERIC_SCALE

		FROM @@DATABASE@@.INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_SCHEMA = '@@SCHEMA@@' AND TABLE_NAME = '@@TABLE@@'
	''',
    "schema_to_oracle": '''
		SELECT
			TABLE_CATALOG
			,TABLE_NAME
			,TABLE_SCHEMA
			,CONCAT(COLUMN_NAME, ' ', UPPER(DATA_TYPE),
				CASE 
					WHEN DATA_TYPE LIKE '%int' THEN ''
					WHEN DATA_TYPE IN ('decimal', 'numeric') THEN CONCAT(' (', NUMERIC_PRECISION, ', ',  NUMERIC_SCALE, ')')
					WHEN DATA_TYPE LIKE '%char' THEN CONCAT(' (', CHARACTER_MAXIMUM_LENGTH, ')')
				END,
				IIF(IS_NULLABLE = 'YES', ' NULL', ' NOT NULL')
			) AS SYNTAXIS

		FROM @@DATABASE@@.INFORMATION_SCHEMA.COLUMNS

		WHERE TABLE_SCHEMA = '@@SCHEMA@@' AND TABLE_NAME = '@@TABLE@@'
		'''
	},
    
    "oracle": {
        "TableCreation": '''
		CREATE TABLE
		'''
	}
}